version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - sqlite-data:/usr/src/app/dev.db
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=sqlite:/usr/src/app/dev.db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  sqlite-data:

